version: "3.8"

services:
  node_backend:
    container_name: node-bookStore
    image: nodeBookStore
    build:
      context: .
    ports:
      - "3001:3001"
    depends_on:
      - node_db
  node_db:
    container_name: node_db
    image: "postgres:12"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=demo
      - POSTGRES_PASSWORD=demo
      - POSTGRES_DB=demo
    volumes:
      - nps_data:/var/lib/postgresql/data

volumes:
  nps_data: {}
